# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditionee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dancer_number', models.IntegerField()),
                ('choreographer', models.BooleanField(default=False)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('middle_initial', models.CharField(max_length=1)),
                ('last_name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DancerSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=7)),
                ('day', models.PositiveSmallIntegerField()),
                ('value', models.BooleanField(default=False)),
                ('audition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Auditionee')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('audition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=7)),
                ('day', models.PositiveSmallIntegerField()),
                ('value', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='current',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Semester'),
        ),
        migrations.AddField(
            model_name='auditionee',
            name='dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Dancer'),
        ),
        migrations.AddField(
            model_name='auditionee',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='semesterschedule',
            unique_together=set([('semester', 'time', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='dancerschedule',
            unique_together=set([('audition', 'time', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='auditionee',
            unique_together=set([('semester', 'dancer')]),
        ),
    ]
