# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancerschedule',
            name='day',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='day',
            field=models.CharField(max_length=9),
        ),
    ]
